name: Generate sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate sitemap with sitemap-generator-action
        uses: axel-op/sitemap-generator-action@v2
        with:
          base-url: 'https://decomplicate.github.io'
          ignore: '.github/*'
          output-file: 'sitemap.xml'
          
      - name: Commit and push sitemap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Generate sitemap"
          file_pattern: 'sitemap.xml'
