name: Generate sitemap
on:
  push:
    branches: [main] 
jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://decomplicate.github.io/
      - name: Commit sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Auto-generate sitemap"
          git push
