name: Generate sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate sitemap from files
        uses: jakejarvis/sitemap-generator@v2
        with:
          base_url: 'https://decomplicate.github.io/'

      - name: Commit and push sitemap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Generate sitemap"
          file_pattern: 'sitemap.xml'
